version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: org.apache.spark:*
      - dependency-name: org.scala-lang:*
      - dependency-name: org.pac4j:*
      - dependency-name: org.antlr:*
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
