version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Although we're happy to keep legend-delta up to date with legend development
      # upgrading to spark core dependencies is more critical
      - dependency-name: org.apache.spark:*
      - dependency-name: org.scala-lang:*
      - dependency-name: io.delta:*
      - dependency-name: org.pac4j:*
      - dependency-name: org.antlr:*
      # ignoring maven plugins
      - dependency-name: org.apache.maven.plugins:*
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: pyspark